### PR TITLE
Update boards.txt

### PR DESCRIPTION
**Pull request by dvdfreitag**
Added an RF Signal Generator

### CODE REVIEW

**Comment by dvdfreitag** [comment]
It seems like there are issues with files that have spaces in their name:

https://travis-ci.org/monostable/kitnic/builds/152596193#L685

**Comment by dvdfreitag** [comment]
I have updated my repository to remove the gerber files with spaces.

https://github.com/dvdfreitag/Signal-Detector/commit/67e4327730ae99ec85fea7acc8ca1ad158bc5c23

**Comment by kasbah** [comment]
Thanks for the project and your pull-request!

- Looks like there is still some issue rendering the Gerbers even with 67e4327. [Here is a preview](http://pr83.preview.kitnic.it/boards/github.com/dvdfreitag/Signal-Detector/). Could you check your Gerbers with http://viewer.tracespace.io? I'll have a look later when I have more time to see what the issue might be. 
- We are now rendering readmes, if you put a little bit of explanation in a README.md it will appear on the page and make it much more approachable.

**Comment by dvdfreitag** [comment]
tracespace

This is the preview that I get on http://viewer.tracespace.io/. To be sure there aren't any issues between the gerber files in my repository and in your preview, I generated this image with the gerber files downloaded from that preview link. 

It seems to me your renderer is does not like the file extensions. I had to manually set the layer types on the tracespace viewer. I imagine this is the issue.

**Comment by dvdfreitag** [comment]
Also, I finally got around to adding a readme.

https://github.com/dvdfreitag/Signal-Detector/commit/6978ba247948e1a5631f9671909d77d109ff48ec

**Comment by kasbah** [comment]
Ah, this is an issue with [tracespace/whats-that-gerber](https://github.com/tracespace/whats-that-gerber) then. I see this is a Eagle project but they are not the default names. Is it some sort of standard you are using or is this a custom output script?

At some point I will get around to adding a manual map as outlined in #12.

**Comment by dvdfreitag** [comment]
These files are generated using the OSH Park CAM files for Cadsoft Eagle. Personally I prefer their naming convention because it's immediately apparent which layers are which.

http://docs.oshpark.com/design-tools/eagle/cam-job/

**Comment by kasbah** [comment]
Ok, cool, I will add these to whats-that-gerber (or you could add them, if you feel so inclined). http://pr83.preview.kitnic.it should update with the README soon. Unless you spot any other issues it should then be good to go up on the main site once whats-that-gerber is updated.

**Comment by kasbah** [comment]
Whats-that-gerber has been updated with your changes (thanks!) and [your board board is up](https://kitnic.it/boards/github.com/dvdfreitag/Signal-Detector/). The page will periodically updated with the latest version from your repository if you want to make any changes. I am sending you some free PCB voucher codes to the email in your GitHub profile because we are running a promotion (not sure if you knew that). Thanks for registering!

**Pull request merged**
