### PR TITLE
Add dynamixel shield in board list

### PR DESCRIPTION
**Pull request by descampsa**
Hey, trying to add my little arduino shield.

All components appear to be found at mouser and digikey, but i was not able to add them to my cart with your chrome extension, so let me know if i did something wrong (1-clik_bom was generated manually from my mouser bom).

### CODE REVIEW

**Comment by kasbah** [comment]
Hey!

Rendering looks great.  [Here is a preview](http://add-dynamixel.preview.kitnic.it/boards/github.com/descampsa/DynamixelShield/).  It would be good if you could still add the part numbers for Mouser and Digikey into the BOM even if the extension didn't work for you.

Also, would be very interested to hear why it didn't work: 

- What did _you_ do? 
- What where you expecting it to do? 
- What did it do instead?

**Comment by descampsa** [comment]
The autocomplete process worked, i just wasn't sure if the 1-click-bom should be the one obtained after the autocomplete process, or before. I will update it with mouser/digikey part numbers.

As for the problem i encountered with your extension, it doesn't seem specific to my board, so i will open a separate issue.

**Comment by kasbah** [comment]
The auto complete process isn't that good yet unfortunately, you will have to check over the BOM yourself after doing it. If you have confirmed correct parts for Digikey and Mouser just use those but it seems you also have some very large MOQ items for Digikey, would be good if you could select ones which are available in lower quantities. 

bom1

**Comment by descampsa** [comment]
Hmm, indeed, for digikey in US, i get a 12000$ total, that might be a little bit too expensive :laughing:
Note that results vary wildly by country, for my country (belgium), those items simply fail to be added to the cart (even if they are available on digikey.be).

I will have a look to see if i can find equivalent parts with better availability.

**Comment by descampsa** [comment]
I have updated the bom with equivalent parts, and now both mouser and digikey carts looks ok, with no minimum quantity (for belgium version, at least, i have not tested other countries). 

Other suppliers are still largely incomplete, but can you accept it as it is for now?

By the way, i noticed that the autocomplete script sometimes miss obvious things : for example, the NTD4904NT4G mosfet can be found easily with the part number on [RS](http://befr.rs-online.com/web/p/mosfet-transistors/7800539/?searchTerm=NTD4904NT4G), but is not found by the script.

**Comment by kasbah** [comment]
Could you just remove the parts you are not sure about please? No point in having wrong parts on there. Otherwise I am happy to merge this in. I also need a private way to contact you for your voucher code. 

Yeah, I have some plans for improving the auto complete. Right now it mostly just grabs the first result from Octopart.com and tries Findchips.com if it can't find it on Octopart.

**Comment by descampsa** [comment]
Ok, i have removed a few non sensical parts, all parts that remain now seem correct, though sometimes with huge minimum quantities.

Yet another quirk (sorry ;-)) : for some parts (molex 22-28-4030 and 22-05-7035), the script add the manufacturer part number after the newark number. 
Those parts then fail to add correcty to the cart, i add to fix them manually (remove manufacturer number).

**Comment by kasbah** [comment]
Hey, this is merged and up: https://kitnic.it/boards/github.com/descampsa/dynamixelshield/

Voucher code sent. I am not sure which script you are referring to with your Molex part number issue. Is it one of the KiCAD output scripts?

**Comment by descampsa** [comment]
Great. I have received the voucher code, thank you very much.

No, i was still refering to the autocomplete functionnality.

**Comment by kasbah** [comment]
Hmm, I couldn't reproduce that. I tried running auto-complete on your current BOM.

**Comment by descampsa** [comment]
You have to start from a non completed bom (only refs, qty, description and mpn cols)

**Comment by kasbah** [comment]
Ah, thanks, I'll try and reproduce it again later. It isn't working for me at all right now :/. That part definitely needs a lot of work before it will be really useful

**Pull request merged**
