### PR TITLE
Added piezo sensor project

### PR DESCRIPTION
**Pull request by DefProc**
I've had a go at this. The 1-click-bom file generated cleanly, but I'm interested to see what happens with the piezo component, as my normal supplier is not one of the supported ones.

### CODE REVIEW

**Comment by kasbah** [comment]
Hi! Thanks! https://git.defproc.co.uk/DefProc/piezo-sensor is not publicly accessible though.

**Comment by DefProc** [comment]
Ooops, that won't help! :neutral_face: 

Fixed, the repo is not publicly available.

**Comment by kasbah** [comment]
Looks good to me: http://add-piezo-sensor.preview.kitnic.it/boards/git.defproc.co.uk/DefProc/piezo-sensor/

Let me know if you are happy with it. Maybe [this Farnell item](http://uk.farnell.com/murata/7bb-20-6l0/sounder-6-3khz-ext-drive/dp/1192520) would be a good alternative for the Piezo?

**Comment by kasbah** [comment]
the site link gives a 404: http://defproc.co.uk/project/piezo

**Comment by DefProc** [comment]
I've updated my end so the project link points to the proper page, included a "build-it" link out the the expected kitnic.it page url.

In the repo, I've tidied the readme and added the piezo and some RS and digikey alternative parts. 

I'm happy for you deploy :smile: :+1:

**Comment by kasbah** [comment]
Thanks for registering! I've merged it and sending you a voucher code via Twitter. Still getting a 404 on the site link though.

**Comment by kasbah** [comment]
It's up: https://kitnic.it/boards/git.defproc.co.uk/DefProc/piezo-sensor/

**Comment by DefProc** [comment]
Ah, found the misspelling in the kitnic.yaml. The change is committed and
ready when you next rebuild.

Thanks

**Pull request merged**
