### PR TITLE
Fixes #65

### LINKED ISSUE #65: SVG rendering in project page can be much smaller than in the thumb/cards
https://saucelabs.com/beta/tests/4d4a7311515649cea9d503672376ec02

0002screenshot

0003screenshot

### PR DESCRIPTION
**Pull request by slifin**
Fixes specificity issues introduced during linting

#65

### CODE REVIEW

**Comment by kasbah** [comment]
This doesn't seem to address #65 at all?

https://saucelabs.com/beta/manual/f85efafca40340e490a2dea240bdb656

**Comment by slifin** [comment]
These are the differences at time of writing, between this branch and the main branch 
image
image

Some of the old css rules are now being applied again, I made the assumption we were happy with the old max-height as defined in the mobile mode for the SVG (before linting) without checking 

Do you want me to increase max-height to try and match the home page?

**Comment by kasbah** [comment]
Yeah, it really needs to be bigger or at least as big as the home page.

**Comment by kasbah** [comment]
Could you rebase this on master please? I am not sure why merge commits are being listed here.

**Comment by kasbah** [comment]
Also, these can jump out of their containers now. 
0002screenshot

**Comment by slifin** [comment]
The merge was there because I was observing some really odd behaviour where the local was not matching with the remote branch at the time, I still don't fully understand what occurred to ensure I fully understand what is on the branch I'm closing this branch and adding issue-65-2

**Pull request closed without merging**
