### PR TITLE
Fixes #31

### LINKED ISSUE #31: Link to the github repo somewhere

### PR DESCRIPTION
**Pull request by slifin**
Adds a github submission button, and github icon link #31

### CODE REVIEW

**Comment by kasbah** [comment]
I think we need some text there explaining that this is a link to the source code. There is also an issue on Firefox with the title jumping out of the bar:

title_issue

**Comment by kasbah** [comment]
This looks terrible unfortunately. Could we go back to a version like the screenshot above but with a fix for the title bar? I think I'll add a "Fork me on GitHub" banner additionally.

**Comment by kasbah** [comment]
I see you have amended a single commit but you should be able to checkout some of the previous versions of that commit. Check your reflog or https://travis-ci.org/monostable/kitnic/builds and you can checkout `git checkout <7-char-hash>`.

**Comment by kasbah** [comment]
E.g. `git checkout  af3e89c`. Might be easier to get rid of the button styling though.

**Comment by slifin** [comment]
Thank you, I did have a commit state where the title was fixed and it looked like the screenshot, but like you say looks to be easier to revert through refactoring

**Comment by slifin** [comment]
I've updated the branch to closely mimic the screenshot

**Pull request merged**
