### PR TITLE
Add Arduitsy

### PR DESCRIPTION
**Pull request by UDXS**

### CODE REVIEW

**Comment by kasbah** [comment]
Hmm, that seems worse. Why do you only have Qty and "Part" columns now? Also is "can fits" in the description intentional?

No need to close this PR by the way, just update your repo and leave a comment if you think you have fixed everything.

**Comment by UDXS** [comment]
do you have a good example bom?

**Comment by kasbah** [comment]
Sure quite a few, e.g. https://github.com/kasbah/push-on-hold-off/blob/master/1-click-bom.tsv

Are you using [1-click BOM](https://1clickbom.com)?

**Comment by UDXS** [comment]
I will try that

**Comment by kasbah** [comment]
I noticed some more issues:

- You need to add `http://` to the site link
- You should give your work a license otherwise "technically" people are not allowed to download and use the files (I know, it's stupid).

**Comment by UDXS** [comment]
This BOM stuff is actually really hard. I've never done this before, this is my first board.

**Comment by kasbah** [comment]
Yeah, ha, it's a pain. Like I said I am working on some things to make it easier but until then...

Nice job on your first board!

**Comment by UDXS** [comment]
I'm ripping my hair out as I can't find any JST connectors with NEWARE/FARNELL

**Comment by kasbah** [comment]
Sorry, I should have said: you don't need to find parts for _every_ retailer. It's more important that the parts are correct. Looks like you already had all the parts for Digikey specified, that would be enough for someone to buy them.

**Comment by UDXS** [comment]
I DID IT!
1-Click-BOM worked!
Note: not all fields are filled as some are optional

**Comment by kasbah** [comment]
Cool, thanks for persevering. I've restarted the build: https://travis-ci.org/monostable/kitnic/builds/207213049

Should take a few minutes.

**Comment by UDXS** [comment]
thanks

**Comment by kasbah** [comment]
http://add-arduitsy.preview.kitnic.it/boards/github.com/UDXS/Arduitsy/

- I think C1 isn't properly specified (what's the value?)
- Would be good to add the orange LED properly
- I think something must have gone wrong with R1,R2 too

**Comment by UDXS** [comment]
I remade the BOM from scratch and EAGLE doesn't have digikey in it.

**Comment by kasbah** [comment]
But don't you know the part numbers? Where are you going to buy the parts? :laughing:

**Comment by UDXS** [comment]
I'm not sure how to add it to work with 1-click bom.

**Comment by kasbah** [comment]
Just add the Digikey parts in the Digikey column?

I would suggest to work from a spreadsheet and use 1-click BOM to verify. 1-click BOM only really cares about the retailer columns (Digikey, Mouser etc) and you can use it to verify that your retailer parts are correct. You have to verify yourself whether the MPNs are correct yourself for now.

**Comment by UDXS** [comment]
I put MPNs and the Digikey part ids.

**Comment by kasbah** [comment]
http://add-arduitsy.preview.kitnic.it/boards/github.com/UDXS/Arduitsy/

Almost done I think: 

- Website link still needs `http://` added
- The C1 selection for Newark and Mouser are really large minimum order I would suggest instead:
     - Mouser: `581-0805YC104K `
     - Newark:  `94W2909`
- LED1 for Digikey should be: `1497-1188-1-ND` (missing D)
- MCU for Newark should be: 	`68T3810`

**Comment by kasbah** [comment]
Oh, and you still need to give everyone a license to use your work.

**Comment by UDXS** [comment]
thank you so much! I'm fixing it now

**Comment by UDXS** [comment]
Ok, I did it.

**Comment by kasbah** [comment]
Cool, rebuilding now. By the way there is a small grammatical error in the summary, think it should be: 
`A tiny Arduino daughterboard that can fit anywhere!`

**Comment by UDXS** [comment]
I will change it.

**Comment by UDXS** [comment]
I fixed it

**Comment by kasbah** [comment]
Spotted another one, Digikey C1 is really large minimum order as well, would suggest: 478-7961-1-ND

**Comment by UDXS** [comment]
Fixed It

**Comment by UDXS** [comment]
I just found a board error, one second.

**Comment by kasbah** [comment]
Cool, I've re-triggered the build. I gotta go right now but will be back on in an hour to merge this in if everything is ok. 

You can make changes after it's merged in as well so don't stress too much about it.

**Comment by UDXS** [comment]
YAY!

**Comment by kasbah** [comment]
It's up: https://kitnic.it/boards/github.com/udxs/arduitsy/

**Comment by UDXS** [comment]
Cool, thanks

**Comment by kasbah** [comment]
FYI the site link as it is gives a warning that the connection is not secure. You should probably change it to `http` for the time being. 

image

**Comment by UDXS** [comment]
ok

**Pull request merged**
