### PR TITLE
add Logitech G25/G27 shifter/pedals adapter to use as standalone device

### PR DESCRIPTION
**Pull request by robotsrulz**
Please add info about open source/open hardware Logitech G25/G27 shifter/pedals adapter.

### CODE REVIEW

**Comment by kasbah** [comment]
Cool stuff, thanks for the PR.

[This is a preview](http://pr84.preview.kitnic.it/boards/github.com/robotsrulz/SP_Adapter/). The BOM isn't quite right yet as things seem to be in the wrong columns. If you install the [1click BOM extension](https://1clickbom.com) you can give your BOM a test-run.

**Comment by robotsrulz** [comment]
Hi Kaspar!

I fixed the 1-click-bom.tsv, now it loads to 1click BOM extension without any troubles. It was a bit challenging because not all suppliers offer the same parts and auto completion does not offer similar items from other manufacturers. I hope I completed the BOM correctly for each supplier. 

I saw the preview, it looks great, I didn't spot any errors. I hope I'll get some PR from your site too :)

Thanks!

**Comment by kasbah** [comment]
>I hope I completed the BOM correctly for each supplier

You will know that better than I do :). If you do spot any errors in the future Kitnic will pull periodically pull in the latest changes you put on GitHub, so you can still correct it.

Merging now, thanks for registering! I owe you a PCB voucher code since we are running a promo. I need a way to send you the code privately though.

**Comment by robotsrulz** [comment]
I attempted to order all the required parts from each supplier and found some minor mistakes in part numbers for auto-completed positions. I will correct the bom once I doublecheck it again. The project is not very popular at the moment so I don't think someone order parts before I fix it. 

You can contact me privately using email address robots.rulz@gmail.com. Thanks again, you're doing a great job!

**Comment by kasbah** [comment]
Thanks! Voucher code sent, project is up: https://kitnic.it/boards/github.com/robotsrulz/SP_Adapter/

**Pull request merged**
