### PR TITLE
Add Sympetrum-v2 electronic conference badge

### PR DESCRIPTION
**Pull request by borgel**
Excited to make it easier for people to build my widget!

### CODE REVIEW

**Comment by borgel** [comment]
Hmm, CI failed on my BOM TSV, thought the preview tool follows the path in the `kitnic.yml` and previews it properly. Can rename it if you'd like.

**Comment by kasbah** [comment]
You have added the wrong URL! ^_^

**Comment by borgel** [comment]
Haha, you're right! Fixed and rerunning CI now...

**Comment by borgel** [comment]
Hmm, now I don't think I understand the error. Maybe I specified my gerber path incorrectly?

**Comment by kasbah** [comment]
The script couldn't deal with spaces, I fixed it. http://add-sympetrum.preview.kitnic.it/boards/github.com/borgel/sympetrum-v2/

Looks ok right?

**Comment by borgel** [comment]
Yep, looks correct!

**Comment by kasbah** [comment]
Cool, I'll merge this. Can you send me a private contact so I can send you the voucher code (you can email kaspar@kitnic.it)? 

Really like the look of this dragon fly! How does the light communication work? Do people have to hold them together or can it work at a distance?

**Comment by kasbah** [comment]
It's up by the way: https://kitnic.it/boards/github.com/borgel/sympetrum-v2/

**Comment by borgel** [comment]
I see it! Thanks!

I sent you an email.

**Pull request merged**
