### PR TITLE
adding my ideal diode PCB to boards list

### PR DESCRIPTION
**Pull request by kevinb456**

### CODE REVIEW

**Comment by kasbah** [comment]
Thanks kevinb456, this is a preview of your page: http://pr10.preview.kitnic.it/boards/github.com/InaneCoding/KOS01_IdealDiode20A/.

The renderer hasn't recognized the holes, most likely with a KiCad output this is due to the units of the drill file differing from the gerbers. Could you make sure the units used are the same as the gerber (most likely you want mm for both). There should be an option in  the drill output dialog in KiCad.

I am not sure what is wrong with the board outline unfortunately, maybe some gaps? Maybe try out your gerbers with svgerber.github.io once you made the changes.

Also, looks like it brought to light an issue with the thumbnail titles on the main page: http://pr10.preview.kitnic.it/.

**Comment by kevinb456** [comment]
I've copied the drill file into the gerber directory, hopefully this is where it is expected and will solve the holes issue. I've re-exported the gerbers without the odd alignment target. This now looks like it displays correctly on http://svgerber.cousins.io/ . I've also added http:// to the site link and re-exported an updated BOM (still more work to do on the BOM later)

See  commit https://github.com/InaneCoding/KOS01_IdealDiode20A/commit/f70721f08bc5b91a1552b235c422498f529e3609 plus one previously.

**Comment by kasbah** [comment]
Any chance I could entice you to finish this up with some [free PCBs](https://github.com/monostable/kitnic#httpskitnicit)? :smiling_imp:

**Comment by kasbah** [comment]
You can now preview your submission yourself with [kitnic.it/submit/](https://kitnic.it/submit/)!

**Comment by kevinb456** [comment]
Hey, well, I'm slow :) Finally got round to making the few last changes for a v1.0 for kitnic
This now has MPNs in the proper format and the gerbers/drill/BOM etc preview okay on the submission page so I think should be ready to go. Plus I tested it works to a basic level.

The free PCB offer is attractive :) I don't need any of this version but intend to do a v2.0 with lessons learnt from the prototype board and so when I get to that stage some PCBs of that would be very welcome!

Kevin

**Comment by kasbah** [comment]
Ha! Well as long as you keep coming back to it. 

The new submission preview is a bit lax with the BOM unfortunately. You don't have a quantity column! http://add-ideal-diode.preview.kitnic.it/boards/github.com/InaneCoding/KOS01_IdealDiode20A/

**Comment by kevinb456** [comment]
Ah yes, good point. They're all Qty 1 but didn't realise the default Kicad export doesn't have the column.
I've amended.

The submission preview looks really good, very useful to be able to see it on the site with a few click. Some automated checks would be a good addition, maybe with a list of items and then big obvious green (OK), yellow (warning), red (error) for each one at the side as a summary.

**Comment by kasbah** [comment]
Your project is up: https://kitnic.it/boards/github.com/inanecoding/kos01_idealdiode20a/

Re: preview, there is actually a little error/warning area already (e.g. if you try and use an invalid URL) but we need to actually parse and validate the BOM like it's done to make the actual page.

**Pull request merged**
