### PR TITLE
Added USBvil board

### PR DESCRIPTION
**Pull request by JarrettR**

### CODE REVIEW

**Comment by kasbah** [comment]
Oooff Travis took a long time on this, sorry about that. Probably worth thinking about caching the build to speed it up short-term.

Here is a preview of your page: http://pr78.preview.kitnic.it/boards/github.com/JarrettR/USBvil/

If you are happy with that I'll merge. You can always request and update to your page by editing registry.json in the future (until we build out the server side at least, by which time updates will likely be fully automated).

**Comment by JarrettR** [comment]
That looks good to me

**Comment by kasbah** [comment]
Thanks very much! The first unsolicited contribution to kitnic.it :)

**Comment by kasbah** [comment]
Here it is: https://kitnic.it/boards/github.com/JarrettR/USBvil/

**Comment by kasbah** [comment]
@JarrettR I am curious as to what people would prefer when they register their project. Should the site just update when you update your repo for now?

**Comment by JarrettR** [comment]
Yeah, periodic rebuilds would seem to make sense, right?

**Comment by kasbah** [comment]
Sounds good, yeah. Can't wait till we have tagged versions though.

**Comment by kasbah** [comment]
Hey @JarrettR, I am running a promotion where when people add their projects to Kitnic they get free PCB service from Dangerous Prototypes. Let me know if you would like to take advantage of that.

**Comment by JarrettR** [comment]
That sounds like a great idea, @kasbah! Should drive interest way up

**Comment by kasbah** [comment]
Fingers crossed, haha. Spread the word, if you can, please. Should I send you a voucher code then?

**Comment by JarrettR** [comment]
Sure, thanks!
:)
Email jrainier@gmail.com

**Comment by kasbah** [comment]
Hey, just a heads-up. We are now rendering the readmes on the [page](https://kitnic.it/boards/github.com/JarrettR/USBvil/#usbvil). Let me know if you see any issues with it.

**Pull request merged**
